export const CREATE_DIARY_REQUEST = "CREATE_DIARY_REQUEST";
export const CREATE_DIARY_SUCCESS = "CREATE_DIARY_SUCCESS";
export const CREATE_DIARY_FAIL = "CREATE_DIARY_FAIL";
export const CREATE_DIARY_RESET = "CREATE_DIARY_RESET";

export const DIARY_LIST_REQUEST = "DIARY_LIST_REQUEST";
export const DIARY_LIST_SUCCESS = "DIARY_LIST_SUCCESS";
export const DIARY_LIST_FAIL = "DIARY_LIST_FAIL";
export const DIARY_LIST_RESET = "DIARY_LIST_RESET";

export const DIARY_UPDATE_REQUEST = "DIARY_UPDATE_REQUEST";
export const DIARY_UPDATE_SUCCESS = "DIARY_UPDATE_SUCCESS";
export const DIARY_UPDATE_FAIL = "DIARY_UPDATE_FAIL";
export const DIARY_UPDATE_RESET = "DIARY_UPDATE_RESET";

export const DIARY_LIST_ID_REQUEST = "DIARY_LIST_ID_REQUEST";
export const DIARY_LIST_ID_SUCCESS = "DIARY_LIST_ID_SUCCESS";
export const DIARY_LIST_ID_FAIL = "DIARY_LIST_ID_FAIL";
export const DIARY_LIST_ID_RESET = "DIARY_LIST_ID_RESET";
