export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_GOOGLE_REQUEST = "USER_LOGIN_GOOGLE_REQUEST";
export const USER_LOGIN_GOOGLE_SUCCESS = "USER_LOGIN_GOOGLE_SUCCESS";
export const USER_LOGIN_GOOGLE_FAIL = "USER_LOGIN_GOOGLE_FAIL";
